export interface ITwilioResponse {
    sid: string,
    dateCreated: string,
    dateUpdated: string,
    dateSent: string,
    accountSid: string,
    to: string,
    from: string,
    body: string,
    status: string,
    numSegments: 1,
    numMedia: string,
    direction: 'inbound-api' | 'outbound-api',
    apiVersion: string,
    price: number,
    priceUnit: number,
    errorCode: number,
    errorMessage: string,
}